### ISSUE TITLE
Update to java 8 u72

### ISSUE THREAD

**Issue by eddykaya** [docker-library/java#64]
Please Update to Java8 u72 in order to get the fixes for the list of issues below:
http://www.oracle.com/technetwork/topics/security/cpujan2016-2367955.html

**Comment by 2d6** [comment]
+1

**Comment by md5** [comment]
I just took a look at the Debian Security Tracker for the various OpenJDK packages:

* [`openjdk-6`](https://security-tracker.debian.org/tracker/source-package/openjdk-6)
* [`openjdk-7`](https://security-tracker.debian.org/tracker/source-package/openjdk-7)
* [`openjdk-8`](https://security-tracker.debian.org/tracker/source-package/openjdk-8)

It looks like the version of the OpenJDK 8 packages for update 72 is currently only fixed in `sid`. It would need to make it into `jessie-backports` (via `stretch`) in order for this image to be updated.

There also seems to be a partially overlapping set of open CVEs in `openjdk-6` and `openjdk-7`.

**Comment by md5** [comment]
More specifically, Debian only lists the `8u72-b15-1` package as fixed.

**Comment by yosifkit** [comment]
Yeah, we have to wait on the debian packaging of openjdk to move into the proper release channels. This is the CVE's from Oracle's list as tracked in Debian:
- [ ] https://security-tracker.debian.org/tracker/CVE-2016-0494
- [ ] https://security-tracker.debian.org/tracker/CVE-2016-0483
- [ ] https://security-tracker.debian.org/tracker/CVE-2016-0475
- [ ] https://security-tracker.debian.org/tracker/CVE-2016-0466
- [ ] https://security-tracker.debian.org/tracker/CVE-2016-0448
- [ ] https://security-tracker.debian.org/tracker/CVE-2016-0402
- [x] https://security-tracker.debian.org/tracker/CVE-2015-7575
- [x] https://security-tracker.debian.org/tracker/CVE-2015-8126

It looks like for java 7 and 8, that the fixes are in `sid` so that means it should be in `testing` (aka `stretch`) in the next couple days.
